name: Sonarqube linux Build for Python

on:
  push:
    branches:
      - main
  #pull_request:
   # types: [opened, synchronize, reopened]


jobs:
  build:
    name: Sonarqube Testing
    runs-on: ubuntu-latest #Can be parametized if needed
    steps:

      - run: sudo apt-get update -y && sudo apt-get install curl -y
      - run: sudo apt-get install jq -y
      - run: sudo apt-get install -y zip
      # - run: sudo apt-get install libxrender1 libfontconfig libxext6 libc6 libxml2 -y

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 #Can be parametized if needed

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  #Can be parametized if needed


      - name : Install Packages 
        run : pip install pytest
      
      - name : Run tests 
        run : pytest test.py  

        working-directory: ./

      - name: Generate Coverage Report
        run:  |
          coverage xml -o coverage.xml
        working-directory: ./

           
      - name: Create Project Properties file
        run: |
          touch sonar-project.properties
          echo "sonar.projectKey=testproj" > sonar-project.properties
          echo "sonar.python.coverage.reportPaths=coverage.xml" >> sonar-project.properties
          Dsonar.python.coverage.reportPaths=coverage.xml
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master 
        
        with:
          projectBaseDir: ./

        env:  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          #SONAR_ROOT_CERT: ${{ secrets.SONAR_QA_CERT }}
      
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
         #SONAR_ROOT_CERT: ${{ secrets.SONAR_QA_CERT }}
